In [2]:
import numpy as np
from sklearn.preprocessing import LabelBinarizer,MultiLabelBinarizer

In [4]:
feature = np.array([['Chennai'],['Madurai'],['Coimbatore'],['Namakkal'],['Chennai'],['Velur'],['Chennai']])

In [5]:
pra = LabelBinarizer()

In [6]:
pra.fit_transform(feature)

array([[1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0]])

In [7]:
pra.classes_

array(['Chennai', 'Coimbatore', 'Madurai', 'Namakkal', 'Velur'],
      dtype='<U10')

In [8]:
pra.inverse_transform(pra.transform(feature))

array(['Chennai', 'Madurai', 'Coimbatore', 'Namakkal', 'Chennai', 'Velur',
       'Chennai'], dtype='<U10')

In [9]:
import pandas as pd

In [10]:
pd.get_dummies(feature[:,0])

Chennai  Coimbatore  Madurai  Namakkal  Velur
0        1           0        0         0      0
1        0           0        1         0      0
2        0           1        0         0      0
3        0           0        0         1      0
4        1           0        0         0      0
5        0           0        0         0      1
6        1           0        0         0      0

In [11]:
multiclass_feature = [('Coimbatore','Chennai'),('Chennai','Madurai'),('Madurai','Tiruchy'),('Namakkal','Velur')]

In [12]:
pra_multi = MultiLabelBinarizer()
pra_multi.fit_transform(multiclass_feature)

array([[1, 1, 0, 0, 0, 0],
       [1, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 1, 0],
       [0, 0, 0, 1, 0, 1]])

In [13]:
pd.get_dummies(multiclass_feature[:,0])

TypeError: list indices must be integers or slices, not tuple

In [14]:
dataframe = pd.DataFrame({'Score': ['low','low','high','high','low','medium']})

In [15]:
scale_maper = {'low':1,'medium':2,'high':3}

In [16]:
dataframe['Score'].replace(scale_maper)

0    1
1    1
2    3
3    3
4    1
5    2
Name: Score, dtype: int64

In [17]:
from sklearn.feature_extraction import DictVectorizer

data_dict = [{'pravin':17,'pranav':18},{'kavin':18,'charan':19},{'pravin':17,'kavin':18},{'charan':19,'pranav':18}]

In [21]:
dict_vector = DictVectorizer(sparse=False)

trans = dict_vector.fit_transform(data_dict)

In [22]:
trans

array([[ 0.,  0., 18., 17.],
       [19., 18.,  0.,  0.],
       [ 0., 18.,  0., 17.],
       [19.,  0., 18.,  0.]])

In [24]:
trans_names = dict_vector.get_feature_names()
trans_names

c:\Users\Pravin P B\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['charan', 'kavin', 'pranav', 'pravin']

In [25]:
from sklearn.neighbors import KNeighborsClassifier

X = np.array([[0,2.34,1.89],[1,5.16,6.17],[0,2.57,1.75],[1,5.78,6.98]])

X_Nan = np.array([[np.nan,1.56,2.85],[np.nan,5.72,6.43]])

clf = KNeighborsClassifier(3,weights='distance')
trained_model = clf.fit(X[:,1:],X[:,0])

imputed_model = trained_model.predict(X_Nan[:,1:])

In [26]:
imputed_model

array([0., 1.])

In [28]:
X_with_predicted = np.hstack((imputed_model.reshape(-1,1),X_Nan[:,1:]))
X_with_predicted

array([[0.  , 1.56, 2.85],
       [1.  , 5.72, 6.43]])

In [29]:
np.vstack((X_with_predicted,X))

array([[0.  , 1.56, 2.85],
       [1.  , 5.72, 6.43],
       [0.  , 2.34, 1.89],
       [1.  , 5.16, 6.17],
       [0.  , 2.57, 1.75],
       [1.  , 5.78, 6.98]])

In [30]:
from sklearn.impute import SimpleImputer


In [33]:
X_complete = np.vstack((X_Nan,X))
imputer = SimpleImputer(strategy='most_frequent')
imputer.fit_transform(X_complete)

array([[0.  , 1.56, 2.85],
       [0.  , 5.72, 6.43],
       [0.  , 2.34, 1.89],
       [1.  , 5.16, 6.17],
       [0.  , 2.57, 1.75],
       [1.  , 5.78, 6.98]])

Imbalanced Classes

In [15]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_iris
import numpy as np

In [16]:
iris = load_iris()
features = iris.data
target = iris.target
target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [17]:
features = features[40:,:]
features

array([[5. , 3.5, 1.3, 0.3],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 3.8, 1.9, 0.4],
       [4.8, 3. , 1.4, 0.3],
       [5.1, 3.8, 1.6, 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [4.9, 2.4, 3.3, 1. ],
       [6.6, 2.9, 4.6, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [5. , 2. , 3.5, 1. ],
       [5.9, 3. , 4.2, 1.5],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.9, 4.7, 1.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.7, 3.1, 4.4, 1.4],
       [5.6, 3. , 4.5, 1.5],
       [5.8, 2.7, 4.1, 1. ],
       [6.2, 2.2, 4.5, 1.5],
       [5.6, 2.5, 3.9, 1.1],
       [5.9, 3.2, 4.8, 1.8],
       [6.1, 2.8, 4. , 1.3],
       [6.3, 2.5, 4.9, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.4, 2

In [18]:
target = target[40:]
target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [19]:
target = np.where((target == 0),0,1)
target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [20]:
weights = {0: .9,1: .1}
RandomForestClassifier(class_weight=weights)

RandomForestClassifier(class_weight={0: 0.9, 1: 0.1})

In [22]:
i_class0 = np.where(target == 0)[0]
i_class1 = np.where(target == 1)[0]
i_class0


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [23]:
i_class1

array([ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,
        23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
        36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,
        49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
        62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,
        75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
        88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100,
       101, 102, 103, 104, 105, 106, 107, 108, 109], dtype=int64)

In [25]:
n_class0 = len(i_class0)
n_class1 = len(i_class1)
n_class0

10

In [26]:
n_class1

100

DownSampling

In [27]:
i_class1_downsampled = np.random.choice(i_class1 , size = n_class0, replace=False)
i_class1_downsampled

array([ 84,  65,  21,  59,  69,  46,  31, 105,  28,  64], dtype=int64)

In [28]:
target[i_class1_downsampled]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [29]:
np.hstack((target[i_class0], target[i_class1_downsampled]))

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [32]:
np.vstack((features[i_class0] , features[i_class1_downsampled]))

array([[5. , 3.5, 1.3, 0.3],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 3.8, 1.9, 0.4],
       [4.8, 3. , 1.4, 0.3],
       [5.1, 3.8, 1.6, 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [6.7, 3.3, 5.7, 2.1],
       [7.6, 3. , 6.6, 2.1],
       [5.9, 3. , 4.2, 1.5],
       [5.7, 2.8, 4.1, 1.3],
       [7.2, 3.6, 6.1, 2.5],
       [6.7, 3.1, 4.7, 1.5],
       [6.1, 2.8, 4. , 1.3],
       [6.7, 3. , 5.2, 2.3],
       [6.2, 2.2, 4.5, 1.5],
       [6.5, 3. , 5.8, 2.2]])

UP sampling

In [33]:
i_class0_upsampled = np.random.choice(i_class0 , size=n_class1, replace=True)

In [34]:
np.hstack((target[i_class0_upsampled], target[i_class1]))

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1])

In [35]:
np.hstack((features[i_class0_upsampled] , features[i_class1]))

array([[5. , 3.5, 1.3, 0.3, 7. , 3.2, 4.7, 1.4],
       [4.4, 3.2, 1.3, 0.2, 6.4, 3.2, 4.5, 1.5],
       [5. , 3.3, 1.4, 0.2, 6.9, 3.1, 4.9, 1.5],
       [5. , 3.3, 1.4, 0.2, 5.5, 2.3, 4. , 1.3],
       [5.3, 3.7, 1.5, 0.2, 6.5, 2.8, 4.6, 1.5],
       [5.3, 3.7, 1.5, 0.2, 5.7, 2.8, 4.5, 1.3],
       [5. , 3.3, 1.4, 0.2, 6.3, 3.3, 4.7, 1.6],
       [4.8, 3. , 1.4, 0.3, 4.9, 2.4, 3.3, 1. ],
       [5. , 3.5, 1.3, 0.3, 6.6, 2.9, 4.6, 1.3],
       [4.4, 3.2, 1.3, 0.2, 5.2, 2.7, 3.9, 1.4],
       [5. , 3.5, 1.3, 0.3, 5. , 2. , 3.5, 1. ],
       [5. , 3.5, 1.3, 0.3, 5.9, 3. , 4.2, 1.5],
       [5.3, 3.7, 1.5, 0.2, 6. , 2.2, 4. , 1. ],
       [4.4, 3.2, 1.3, 0.2, 6.1, 2.9, 4.7, 1.4],
       [5.3, 3.7, 1.5, 0.2, 5.6, 2.9, 3.6, 1.3],
       [4.6, 3.2, 1.4, 0.2, 6.7, 3.1, 4.4, 1.4],
       [4.5, 2.3, 1.3, 0.3, 5.6, 3. , 4.5, 1.5],
       [4.4, 3.2, 1.3, 0.2, 5.8, 2.7, 4.1, 1. ],
       [5. , 3.5, 1.6, 0.6, 6.2, 2.2, 4.5, 1.5],
       [5. , 3.3, 1.4, 0.2, 5.6, 2.5, 3.9, 1.1],
       [4.5, 2.3, 1.