In [2]:
import numpy as np
from sklearn.preprocessing import LabelBinarizer,MultiLabelBinarizer

In [4]:
feature = np.array([['Chennai'],['Madurai'],['Coimbatore'],['Namakkal'],['Chennai'],['Velur'],['Chennai']])

In [5]:
pra = LabelBinarizer()

In [6]:
pra.fit_transform(feature)

array([[1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0]])

In [7]:
pra.classes_

array(['Chennai', 'Coimbatore', 'Madurai', 'Namakkal', 'Velur'],
      dtype='<U10')

In [8]:
pra.inverse_transform(pra.transform(feature))

array(['Chennai', 'Madurai', 'Coimbatore', 'Namakkal', 'Chennai', 'Velur',
       'Chennai'], dtype='<U10')

In [9]:
import pandas as pd

In [10]:
pd.get_dummies(feature[:,0])

Chennai  Coimbatore  Madurai  Namakkal  Velur
0        1           0        0         0      0
1        0           0        1         0      0
2        0           1        0         0      0
3        0           0        0         1      0
4        1           0        0         0      0
5        0           0        0         0      1
6        1           0        0         0      0

In [11]:
multiclass_feature = [('Coimbatore','Chennai'),('Chennai','Madurai'),('Madurai','Tiruchy'),('Namakkal','Velur')]

In [12]:
pra_multi = MultiLabelBinarizer()
pra_multi.fit_transform(multiclass_feature)

array([[1, 1, 0, 0, 0, 0],
       [1, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 1, 0],
       [0, 0, 0, 1, 0, 1]])

In [13]:
pd.get_dummies(multiclass_feature[:,0])

TypeError: list indices must be integers or slices, not tuple

In [14]:
dataframe = pd.DataFrame({'Score': ['low','low','high','high','low','medium']})

In [15]:
scale_maper = {'low':1,'medium':2,'high':3}

In [16]:
dataframe['Score'].replace(scale_maper)

0    1
1    1
2    3
3    3
4    1
5    2
Name: Score, dtype: int64

In [17]:
from sklearn.feature_extraction import DictVectorizer

data_dict = [{'pravin':17,'pranav':18},{'kavin':18,'charan':19},{'pravin':17,'kavin':18},{'charan':19,'pranav':18}]

In [21]:
dict_vector = DictVectorizer(sparse=False)

trans = dict_vector.fit_transform(data_dict)

In [22]:
trans

array([[ 0.,  0., 18., 17.],
       [19., 18.,  0.,  0.],
       [ 0., 18.,  0., 17.],
       [19.,  0., 18.,  0.]])

In [24]:
trans_names = dict_vector.get_feature_names()
trans_names

c:\Users\Pravin P B\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['charan', 'kavin', 'pranav', 'pravin']

In [25]:
from sklearn.neighbors import KNeighborsClassifier

X = np.array([[0,2.34,1.89],[1,5.16,6.17],[0,2.57,1.75],[1,5.78,6.98]])

X_Nan = np.array([[np.nan,1.56,2.85],[np.nan,5.72,6.43]])

clf = KNeighborsClassifier(3,weights='distance')
trained_model = clf.fit(X[:,1:],X[:,0])

imputed_model = trained_model.predict(X_Nan[:,1:])

In [26]:
imputed_model

array([0., 1.])

In [28]:
X_with_predicted = np.hstack((imputed_model.reshape(-1,1),X_Nan[:,1:]))
X_with_predicted

array([[0.  , 1.56, 2.85],
       [1.  , 5.72, 6.43]])

In [29]:
np.vstack((X_with_predicted,X))

array([[0.  , 1.56, 2.85],
       [1.  , 5.72, 6.43],
       [0.  , 2.34, 1.89],
       [1.  , 5.16, 6.17],
       [0.  , 2.57, 1.75],
       [1.  , 5.78, 6.98]])

In [30]:
from sklearn.impute import SimpleImputer


In [33]:
X_complete = np.vstack((X_Nan,X))
imputer = SimpleImputer(strategy='most_frequent')
imputer.fit_transform(X_complete)

array([[0.  , 1.56, 2.85],
       [0.  , 5.72, 6.43],
       [0.  , 2.34, 1.89],
       [1.  , 5.16, 6.17],
       [0.  , 2.57, 1.75],
       [1.  , 5.78, 6.98]])